spring:
  profiles: dev

logging:
  level:
    root: info

io:
  remedymatch:
    keycloak:
      url: https://localhost:8090/auth
      realm: master
      username: admin
      password: Pa55w0rd
      adminCli: admin-cli
    engine:
      url: http://localhost:8085

